solved error failed to insatiate module
vendor.min.js:13 Uncaught Error: [$injector:modulerr] Failed to
instantiate module DojoIBL due to:
Error: [$injector:modulerr] Failed to instantiate module firebase due
to:
Error: [$injector:nomod] Module 'firebase' is not available! You either
misspelled the module name or forgot to load it. If registering a
module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.9/$injector/nomod?p0=firebase